name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Install cross-compiler
            run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-none-linux-gnu
          - name: Run full test (with correct CROSS_COMPILE)
            run: |
              export CROSS_COMPILE=aarch64-none-linux-gnu-
              ./full-test.sh
