name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
jobs:
  unit-test:
    container: cuaesd/aesd-autotest:24-unit-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    container: cuaesd/aesd-autotest:24-assignment3
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      # Ensure Busybox repo clone is retried if it fails
      - name: Clone busybox repository with retry
        run: |
          n=0
          until [ $n -ge 3 ]
          do
            git clone --depth=1 https://busybox.net/busybox.git busybox && break
            n=$((n+1))
            sleep 5
          done

      # Ensure initrd image exists before running tests
      - name: Prepare initrd image
        run: |
          mkdir -p /tmp/aesd-autograder
          if [ ! -f /tmp/aesd-autograder/initramfs.cpio.gz ]; then
             echo "Missing initramfs.cpio.gz, please ensure it is created or copied here."
             exit 1
          fi

      # Run the full test with increased timeout
      - name: Run full test
        run: timeout --preserve-status 120s ./full-test.sh

      # Docker cleanup with permissions handled
      - name: Cleanup Docker (ignore errors)
        run: |
          docker rm --force $(docker ps -aq) || true
          docker network prune -f || true
